### ISSUE TITLE
FIELD REPORT TABLE GOT REKT

### ISSUE THREAD

**Issue by seanseany** [jonathankoh95/absolute#13]
Do you know what happened to the field report table?

Here is what it looks like for me:
<img width="869" alt="screen shot 2016-08-04 at 7 37 01 pm" src="https://cloud.githubusercontent.com/assets/7416639/17421820/eb208368-5a7a-11e6-9a2e-d20ea4237f39.png">

- Why is there text behind the labels?
- Why is there an extra column?

**Comment by jonathankoh95** [comment]
LOLOL. i think its cause of the conflicts i solved it though. did you sync?

**Comment by jonathankoh95** [comment]
shld be solid now!
