### ISSUE TITLE
FORMS FOR FLUFFY

### ISSUE THREAD

**Issue by jonathankoh95** [jonathankoh95/absolute#17]
yo bruh if you have time

LOGIN PAGE

CREATE NEW USER ACC FORM 
- Username + Password

CREATE NEW ACCOUNT INFORMATION FORM
- First Name, last name, etc etc. follow template form old ejs

UPDATE NEW ACCOUNT INFORMATION FORM
- Maybe same form as new acc form?
- ADD OPTION TO CHANGE DESIGNATION
       - list of possible designations: Field Representative, Leader, Team Leader, Senior Team Leader, Assistant Owner, Owner

**Comment by jonathankoh95** [comment]
OH YEAH and the header for nav too

**Comment by seanseany** [comment]
Login page done

**Comment by seanseany** [comment]
sign up done
