### ISSUE TITLE
Line 123-127 of fieldReport.ejs

### ISSUE THREAD

**Issue by seanseany** [jonathankoh95/absolute#5]
Show Total only when there is data, similar to the sales people. Not sure how v-if works. See if you can resolve.

**Comment by jonathankoh95** [comment]
GOT IT! i rendered the data so that if there are no sales for the day salesData = null. so gotta check that

**Comment by jonathankoh95** [comment]
Regarding AM, PM and SS. (SS = full day) we needa put it for each individual cause its different for each. if you look on the field report table i already tagged it below each salesman.

**Comment by seanseany** [comment]
**FIELD REPORT TABLE**
- Still no Sales Total when there is data
- Ok i'll add AM PM for each salesman, keep issue open if you want stuff done

**Comment by jonathankoh95** [comment]
yo did you sync it. i feel like its working for mine
